# Generated by Django 5.2 on 2025-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18-30", "18-30"),
                    ("31-45", "31-45"),
                    ("46-65", "46-65"),
                    ("65+", "65+"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
