# Generated by Django 5.2 on 2025-04-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="nationality",
        ),
        migrations.AddField(
            model_name="profile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary_school", "Primary School"),
                    ("high_school", "High School"),
                    ("bachelor", "Bachelor's Degree"),
                    ("master", "Master's Degree"),
                    ("phd", "PhD"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
