# Generated by Django 5.2 on 2025-04-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_profile_nationality_profile_education_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
