# Generated by Django 5.2 on 2025-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
