# Generated by Django 5.2 on 2025-04-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey_api", "0002_alter_survey_deadline"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="response",
            name="unique_user_survey_response",
        ),
    ]
