# Generated by Django 5.1.3 on 2025-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0003_remove_response_unique_user_survey_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='surveys/'),
        ),
    ]
