# Generated by Django 5.1.3 on 2025-05-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0004_survey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='definition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
