# Generated by Django 5.1.3 on 2025-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0005_organization_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
